In [2]:
# Cargamos los datasets
import pandas as pd
from pandas import read_csv
# load the dataset
dataset_1 = read_csv('Saber_11__2019-1.csv')
dataset_2 = read_csv('Saber_11__2019-2.csv')


# Concatenamos los datasets
dataset = pd.concat([dataset_1, dataset_2])

#display(dataset.values)

# summarize the dataset
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', -1)
print(dataset.describe())

display(dataset.values)

/Users/alpha/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3071: DtypeWarning: Columns (76,78) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
<ipython-input-2-7279402e2571>:18: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option('display.max_colwidth', -1)

             PERIODO  COLE_CODIGO_ICFES  COLE_COD_DANE_ESTABLECIMIENTO  \
count  567295.000000  567295.000000      5.672950e+05
mean   20193.888508   195331.487896      2.088907e+11
std    0.567492       228307.567910      9.473532e+10
min    20191.000000   75.000000          1.050010e+11
25%    20194.000000   45393.000000       1.190010e+11
50%    20194.000000   112128.000000      1.760010e+11
75%    20194.000000   193102.000000      3.080011e+11
max    20194.000000   728303.000000      8.548740e+11

       COLE_COD_DANE_SEDE  COLE_COD_MCPIO_UBICACION  COLE_COD_DEPTO_UBICACION  \
count  5.672950e+05        567295.000000             567295.000000
mean   2.094468e+11        33053.048913              32.818491
std    9.546011e+10        26562.686743              26.541080
min    1.050010e+11        5001.000000               5.000000
25%    1.190010e+11        11001.000000              11.000000
50%    1.760010e+11        23001.000000              23.000000
75%    3.080011e+11        54001.000000              54.000000
max    8.548740e+11        99773.000000              99.000000

       ESTU_COD_MCPIO_PRESENTACION  ESTU_COD_DEPTO_PRESENTACION  \
count  567295.000000                567295.000000
mean   32999.928182                 32.785239
std    26626.357789                 26.602359
min    5001.000000                  5.000000
25%    11001.000000                 11.000000
50%    20400.000000                 20.000000
75%    54001.000000                 54.000000
max    99773.000000                 99.000000

       PUNT_LECTURA_CRITICA  PERCENTIL_LECTURA_CRITICA  \
count  567295.000000         567295.000000
mean   52.371614             50.126729
std    10.663824             28.956619
min    0.000000              1.000000
25%    45.000000             25.000000
50%    53.000000             50.000000
75%    60.000000             75.000000
max    100.000000            100.000000

       DESEMP_LECTURA_CRITICA  PUNT_MATEMATICAS  PERCENTIL_MATEMATICAS  \
count  567295.000000           567295.000000     567295.00000
mean   2.626801                50.840286         50.12601
std    0.763408                12.175946         28.94543
min    1.000000                0.000000          1.00000
25%    2.000000                42.000000         25.00000
50%    3.000000                51.000000         50.00000
75%    3.000000                59.000000         75.00000
max    4.000000                100.000000        100.00000

       DESEMP_MATEMATICAS  PUNT_C_NATURALES  PERCENTIL_C_NATURALES  \
count  567295.000000       567295.000000     567295.000000
mean   2.452846            48.480397         50.171274
std    0.759428            10.952288         28.933891
min    1.000000            0.000000          1.000000
25%    2.000000            40.000000         25.000000
50%    3.000000            48.000000         50.000000
75%    3.000000            56.000000         75.000000
max    4.000000            100.000000        100.000000

       DESEMP_C_NATURALES  PUNT_SOCIALES_CIUDADANAS  \
count  567295.000000       567295.000000
mean   2.036750            46.521646
std    0.772901            12.330779
min    1.000000            0.000000
25%    1.000000            37.000000
50%    2.000000            45.000000
75%    3.000000            56.000000
max    4.000000            100.000000

       PERCENTIL_SOCIALES_CIUDADANAS  DESEMP_SOCIALES_CIUDADANAS  \
count  567295.000000                  567295.000000
mean   50.193125                      1.920858
std    28.910539                      0.832658
min    1.000000                       1.000000
25%    25.000000                      1.000000
50%    50.000000                      2.000000
75%    75.000000                      3.000000
max    100.000000                     4.000000

         PUNT_INGLES  PERCENTIL_INGLES    PUNT_GLOBAL  \
count  567276.000000  567295.000000     567295.000000
mean   48.863158      50.114773         247.501457
std    13.020856      28.916369         52.440962
min    0.000000       1.000000          0.000000
25%    39.000000      25.000000         208.000000
50%    48.000000      50.000000         244.000000
75%    57.000000      75.000000         284.000000
max    100.000000     100.000000        477.000000

       ESTU_NSE_ESTABLECIMIENTO
count  567247.000000
mean   2.406137
std    0.707315
min    1.000000
25%    2.000000
50%    2.000000
75%    3.000000
max    4.000000

array([['TI', 'COLOMBIA', 'F', ..., 3.0, 'PUBLICAR', 'NO'],
       ['CC', 'COLOMBIA', 'F', ..., 3.0, 'PUBLICAR', 'NO'],
       ['TI', 'COLOMBIA', 'M', ..., 3.0, 'PUBLICAR', 'NO'],
       ...,
       ['TI', 'COLOMBIA', 'M', ..., 3.0, 'PUBLICAR',
        'GENERACION E - EXCELENCIA DEPARTAMENTAL'],
       ['TI', 'COLOMBIA', 'M', ..., 2.0, 'PUBLICAR',
        'GENERACION E - GRATUIDAD'],
       ['TI', 'COLOMBIA', 'M', ..., 3.0, 'PUBLICAR',
        'GENERACION E - EXCELENCIA NACIONAL']], dtype=object)

In [3]:
display(dataset.values)

array([['TI', 'COLOMBIA', 'F', ..., 3.0, 'PUBLICAR', 'NO'],
       ['CC', 'COLOMBIA', 'F', ..., 3.0, 'PUBLICAR', 'NO'],
       ['TI', 'COLOMBIA', 'M', ..., 3.0, 'PUBLICAR', 'NO'],
       ...,
       ['TI', 'COLOMBIA', 'M', ..., 3.0, 'PUBLICAR',
        'GENERACION E - EXCELENCIA DEPARTAMENTAL'],
       ['TI', 'COLOMBIA', 'M', ..., 2.0, 'PUBLICAR',
        'GENERACION E - GRATUIDAD'],
       ['TI', 'COLOMBIA', 'M', ..., 3.0, 'PUBLICAR',
        'GENERACION E - EXCELENCIA NACIONAL']], dtype=object)

In [23]:
print(dataset.head(5))

  ESTU_TIPODOCUMENTO ESTU_NACIONALIDAD ESTU_GENERO ESTU_FECHANACIMIENTO  \
0  TI                 COLOMBIA          F           07/12/2000
1  CC                 COLOMBIA          F           23/03/1998
2  TI                 COLOMBIA          M           22/03/2001
3  CC                 COLOMBIA          M           16/06/1994
4  CC                 COLOMBIA          F           21/09/2000

   PERIODO  ESTU_CONSECUTIVO ESTU_ESTUDIANTE ESTU_PAIS_RESIDE ESTU_TIENEETNIA  \
0  20191    SB11201910008548  ESTUDIANTE      COLOMBIA         No
1  20191    SB11201910004475  ESTUDIANTE      COLOMBIA         No
2  20191    SB11201910011427  ESTUDIANTE      COLOMBIA         No
3  20191    SB11201910041975  ESTUDIANTE      COLOMBIA         No
4  20191    SB11201910014490  ESTUDIANTE      COLOMBIA         No

  ESTU_ETNIA ESTU_DEPTO_RESIDE ESTU_COD_RESIDE_DEPTO ESTU_MCPIO_RESIDE  \
0  -          VALLE             76                    CALI
1  -          VALLE             76                    CALI
2  -          VALLE             76                    CALI
3  -          VALLE             76                    CALI
4  -          BOGOTA            11                    BOGOTÁ D.C.

  ESTU_COD_RESIDE_MCPIO FAMI_ESTRATOVIVIENDA FAMI_PERSONASHOGAR  \
0  76001                 Estrato 4            3 a 4
1  76001                 Estrato 3            7 a 8
2  76001                 Estrato 2            5 a 6
3  76001                 Estrato 2            3 a 4
4  11001                 Estrato 6            3 a 4

  FAMI_CUARTOSHOGAR               FAMI_EDUCACIONPADRE  \
0  Cuatro            Técnica o tecnológica incompleta
1  Cuatro            Técnica o tecnológica completa
2  Cuatro            Primaria incompleta
3  Dos               Educación profesional completa
4  Tres              Educación profesional completa

                  FAMI_EDUCACIONMADRE  \
0  Secundaria (Bachillerato) completa
1  Secundaria (Bachillerato) completa
2  Educación profesional completa
3  Educación profesional completa
4  Educación profesional completa

                                                                                 FAMI_TRABAJOLABORPADRE  \
0  Trabaja como profesional (por ejemplo médico, abogado, ingeniero)
1  Trabaja por cuenta propia (por ejemplo plomero, electricista)
2  Es dueño de un negocio pequeño (tiene pocos empleados o no tiene, por ejemplo tienda, papelería, etc
3  Trabaja como profesional (por ejemplo médico, abogado, ingeniero)
4  Trabaja como profesional (por ejemplo médico, abogado, ingeniero)

                                                                   FAMI_TRABAJOLABORMADRE  \
0  Trabaja en el hogar, no trabaja o estudia
1  Trabaja en el hogar, no trabaja o estudia
2  Tiene un trabajo de tipo auxiliar administrativo (por ejemplo, secretario o asistente)
3  Trabaja en el hogar, no trabaja o estudia
4  Trabaja en el hogar, no trabaja o estudia

  FAMI_TIENEINTERNET FAMI_TIENESERVICIOTV FAMI_TIENECOMPUTADOR  \
0  Si                 Si                   Si
1  Si                 Si                   No
2  Si                 Si                   No
3  Si                 Si                   Si
4  Si                 Si                   Si

  FAMI_TIENELAVADORA FAMI_TIENEHORNOMICROOGAS FAMI_TIENEAUTOMOVIL  \
0  Si                 Si                       No
1  Si                 No                       No
2  Si                 Si                       No
3  No                 Si                       No
4  Si                 Si                       Si

  FAMI_TIENEMOTOCICLETA FAMI_TIENECONSOLAVIDEOJUEGOS     FAMI_NUMLIBROS  \
0  No                    No                           0 A 10 LIBROS
1  No                    No                           11 A 25 LIBROS
2  No                    Si                           0 A 10 LIBROS
3  Si                    No                           0 A 10 LIBROS
4  No                    Si                           MÁS DE 100 LIBROS

       FAMI_COMELECHEDERIVADOS    FAMI_COMECARNEPESCADOHUEVO  \
0  Todos o casi todos los días  3 a 5 veces por semana
1  3 a 5 veces por semana       Todos o casi todos los días
2  3 a 5 veces por semana       Nunca o rara vez comemos eso
3  1 o 2 veces por semana       1 o 2 veces por semana
4  Todos o casi todos los días  Todos o casi todos los días

  FAMI_COMECEREALFRUTOSLEGUMBRE FAMI_SITUACIONECONOMICA  \
0  Todos o casi todos los días   Mejor
1  Nunca o rara vez comemos eso  Mejor
2  Nunca o rara vez comemos eso  Igual
3  Nunca o rara vez comemos eso  Igual
4  Todos o casi todos los días   Igual

  ESTU_DEDICACIONLECTURADIARIA ESTU_DEDICACIONINTERNET  \
0  Entre 1 y 2 horas            Entre 1 y 3 horas
1  No leo por entretenimiento   Entre 1 y 3 horas
2  No leo por entretenimiento   30 minutos o menos
3  No leo por entretenimiento   Más de 3 horas
4  Entre 1 y 2 horas            Entre 1 y 3 horas

  ESTU_HORASSEMANATRABAJA ESTU_TIPOREMUNERACION  COLE_CODIGO_ICFES  \
0  0                       No                    114686
1  0                       No                    114686
2  Más de 30 horas         Si, en efectivo       114686
3  Entre 11 y 20 horas     Si, en efectivo       114686
4  0                       No                    19364

   COLE_COD_DANE_ESTABLECIMIENTO  \
0  176001002555
1  176001002555
2  176001002555
3  176001002555
4  311848001011

                                    COLE_NOMBRE_ESTABLECIMIENTO COLE_GENERO  \
0  INSTITUCIÓN EDUCATIVA TÉCNICA COMERCIAL HERNANDO NAVIA VARON  MIXTO
1  INSTITUCIÓN EDUCATIVA TÉCNICA COMERCIAL HERNANDO NAVIA VARON  MIXTO
2  INSTITUCIÓN EDUCATIVA TÉCNICA COMERCIAL HERNANDO NAVIA VARON  MIXTO
3  INSTITUCIÓN EDUCATIVA TÉCNICA COMERCIAL HERNANDO NAVIA VARON  MIXTO
4  COL ANGLO COLOMBIANO                                          MIXTO

  COLE_NATURALEZA COLE_CALENDARIO COLE_BILINGUE      COLE_CARACTER  \
0  OFICIAL         A               N             TÉCNICO/ACADÉMICO
1  OFICIAL         A               N             TÉCNICO/ACADÉMICO
2  OFICIAL         A               N             TÉCNICO/ACADÉMICO
3  OFICIAL         A               N             TÉCNICO/ACADÉMICO
4  NO OFICIAL      B               S             ACADÉMICO

   COLE_COD_DANE_SEDE  \
0  176001002555
1  176001002555
2  176001002555
3  176001002555
4  311848001011

                                                                COLE_NOMBRE_SEDE  \
0  INSTITUCIÓN EDUCATIVA TÉCNICA COMERCIAL HERNANDO NAVIA VARON - SEDE PRINCIPAL
1  INSTITUCIÓN EDUCATIVA TÉCNICA COMERCIAL HERNANDO NAVIA VARON - SEDE PRINCIPAL
2  INSTITUCIÓN EDUCATIVA TÉCNICA COMERCIAL HERNANDO NAVIA VARON - SEDE PRINCIPAL
3  INSTITUCIÓN EDUCATIVA TÉCNICA COMERCIAL HERNANDO NAVIA VARON - SEDE PRINCIPAL
4  COL ANGLO COLOMBIANO

  COLE_SEDE_PRINCIPAL COLE_AREA_UBICACION COLE_JORNADA  \
0  S                   URBANO              NOCHE
1  S                   URBANO              NOCHE
2  S                   URBANO              NOCHE
3  S                   URBANO              NOCHE
4  S                   URBANO              COMPLETA

   COLE_COD_MCPIO_UBICACION COLE_MCPIO_UBICACION  COLE_COD_DEPTO_UBICACION  \
0  76001                     CALI                 76
1  76001                     CALI                 76
2  76001                     CALI                 76
3  76001                     CALI                 76
4  11001                     BOGOTÁ D.C.          11

  COLE_DEPTO_UBICACION ESTU_PRIVADO_LIBERTAD  ESTU_COD_MCPIO_PRESENTACION  \
0  VALLE                N                     76001
1  VALLE                N                     76001
2  VALLE                N                     76001
3  VALLE                N                     76001
4  BOGOTA               N                     11001

  ESTU_MCPIO_PRESENTACION ESTU_DEPTO_PRESENTACION  \
0  CALI                    VALLE
1  CALI                    VALLE
2  CALI                    VALLE
3  CALI                    VALLE
4  BOGOTÁ D.C.             BOGOTA

   ESTU_COD_DEPTO_PRESENTACION  PUNT_LECTURA_CRITICA  \
0  76                           50
1  76                           53
2  76                           60
3  76                           56
4  11                           55

   PERCENTIL_LECTURA_CRITICA  DESEMP_LECTURA_CRITICA  PUNT_MATEMATICAS  \
0  29                         2                       49
1  35                         3                       45
2  54                         3                       52
3  41                         3                       54
4  40                         3                       67

   PERCENTIL_MATEMATICAS  DESEMP_MATEMATICAS  PUNT_C_NATURALES  \
0  31                     2                   47
1  25                     2                   44
2  38                     3                   44
3  43                     3                   46
4  73                     3                   50

   PERCENTIL_C_NATURALES  DESEMP_C_NATURALES  PUNT_SOCIALES_CIUDADANAS  \
0  33                     2                   40
1  27                     2                   34
2  27                     2                   41
3  30                     2                   44
4  38                     2                   47

   PERCENTIL_SOCIALES_CIUDADANAS  DESEMP_SOCIALES_CIUDADANAS  PUNT_INGLES  \
0  22                             1                           54.0
1  10                             1                           35.0
2  23                             2                           49.0
3  29                             2                           64.0
4  34                             2                           71.0

   PERCENTIL_INGLES DESEMP_INGLES  PUNT_GLOBAL PERCENTIL_GLOBAL  \
0  39                A1            235          29
1  10                A-            217          21
2  32                A1            246          34
3  55                A2            255          38
4  64                B1            280          48

  ESTU_INSE_INDIVIDUAL ESTU_NSE_INDIVIDUAL  ESTU_NSE_ESTABLECIMIENTO  \
0  58.1995              3                   3.0
1  51.0185              2                   3.0
2  50.8557              2                   3.0
3  52.6882              3                   3.0
4  73.9308              4                   4.0

  ESTU_ESTADOINVESTIGACION ESTU_GENERACION-E
0  PUBLICAR                 NO
1  PUBLICAR                 NO
2  PUBLICAR                 NO
3  PUBLICAR                 NO
4  PUBLICAR                 NO

In [24]:
num_missing = dataset.isnull().sum()
print(num_missing)

ESTU_TIPODOCUMENTO               0
ESTU_NACIONALIDAD                0
ESTU_GENERO                      0
ESTU_FECHANACIMIENTO             0
PERIODO                          0
ESTU_CONSECUTIVO                 0
ESTU_ESTUDIANTE                  0
ESTU_PAIS_RESIDE                 0
ESTU_TIENEETNIA                  0
ESTU_ETNIA                       0
ESTU_DEPTO_RESIDE                377
ESTU_COD_RESIDE_DEPTO            0
ESTU_MCPIO_RESIDE                377
ESTU_COD_RESIDE_MCPIO            0
FAMI_ESTRATOVIVIENDA             26
FAMI_PERSONASHOGAR               8463
FAMI_CUARTOSHOGAR                6418
FAMI_EDUCACIONPADRE              8292
FAMI_EDUCACIONMADRE              20959
FAMI_TRABAJOLABORPADRE           8131
FAMI_TRABAJOLABORMADRE           7469
FAMI_TIENEINTERNET               8337
FAMI_TIENESERVICIOTV             22280
FAMI_TIENECOMPUTADOR             8185
FAMI_TIENELAVADORA               7643
FAMI_TIENEHORNOMICROOGAS         8630
FAMI_TIENEAUTOMOVIL              8206
FAMI_TIENEMOTOCICLETA            8817
FAMI_TIENECONSOLAVIDEOJUEGOS     7725
FAMI_NUMLIBROS                   8654
FAMI_COMELECHEDERIVADOS          22305
FAMI_COMECARNEPESCADOHUEVO       9625
FAMI_COMECEREALFRUTOSLEGUMBRE    22332
FAMI_SITUACIONECONOMICA          8259
ESTU_DEDICACIONLECTURADIARIA     627
ESTU_DEDICACIONINTERNET          30298
ESTU_HORASSEMANATRABAJA          381
ESTU_TIPOREMUNERACION            15508
COLE_CODIGO_ICFES                0
COLE_COD_DANE_ESTABLECIMIENTO    0
COLE_NOMBRE_ESTABLECIMIENTO      0
COLE_GENERO                      0
COLE_NATURALEZA                  0
COLE_CALENDARIO                  0
COLE_BILINGUE                    0
COLE_CARACTER                    13748
COLE_COD_DANE_SEDE               0
COLE_NOMBRE_SEDE                 0
COLE_SEDE_PRINCIPAL              0
COLE_AREA_UBICACION              0
COLE_JORNADA                     0
COLE_COD_MCPIO_UBICACION         0
COLE_MCPIO_UBICACION             0
COLE_COD_DEPTO_UBICACION         0
COLE_DEPTO_UBICACION             0
ESTU_PRIVADO_LIBERTAD            0
ESTU_COD_MCPIO_PRESENTACION      0
ESTU_MCPIO_PRESENTACION          0
ESTU_DEPTO_PRESENTACION          0
ESTU_COD_DEPTO_PRESENTACION      0
PUNT_LECTURA_CRITICA             0
PERCENTIL_LECTURA_CRITICA        0
DESEMP_LECTURA_CRITICA           0
PUNT_MATEMATICAS                 0
PERCENTIL_MATEMATICAS            0
DESEMP_MATEMATICAS               0
PUNT_C_NATURALES                 0
PERCENTIL_C_NATURALES            0
DESEMP_C_NATURALES               0
PUNT_SOCIALES_CIUDADANAS         0
PERCENTIL_SOCIALES_CIUDADANAS    0
DESEMP_SOCIALES_CIUDADANAS       0
PUNT_INGLES                      19
PERCENTIL_INGLES                 0
DESEMP_INGLES                    0
PUNT_GLOBAL                      0
PERCENTIL_GLOBAL                 0
ESTU_INSE_INDIVIDUAL             850
ESTU_NSE_INDIVIDUAL              17887
ESTU_NSE_ESTABLECIMIENTO         48
ESTU_ESTADOINVESTIGACION         0
ESTU_GENERACION-E                0
dtype: int64

In [4]:
pd.value_counts(dataset['FAMI_TRABAJOLABORMADRE'])

Trabaja en el hogar, no trabaja o estudia                                                               218923
Es dueño de un negocio pequeño (tiene pocos empleados o no tiene, por ejemplo tienda, papelería, etc    49919
Trabaja como personal de limpieza, mantenimiento, seguridad o construcción                              47817
Trabaja como profesional (por ejemplo médico, abogado, ingeniero)                                       46793
Tiene un trabajo de tipo auxiliar administrativo (por ejemplo, secretario o asistente)                  46305
Es vendedor o trabaja en atención al público                                                            41680
No aplica                                                                                               28252
Es agricultor, pesquero o jornalero                                                                     17274
Trabaja por cuenta propia (por ejemplo plomero, electricista)                                           17170
No sabe                                                                                                 12088
-                                                                                                       10885
Es dueño de un negocio grande, tiene un cargo de nivel directivo o gerencial                            10083
Es operario de máquinas o conduce vehículos (taxita, chofer)                                            8729
Pensionado                                                                                              3908
Name: FAMI_TRABAJOLABORMADRE, dtype: int64

In [5]:
pd.value_counts(dataset['FAMI_TIENEINTERNET'])

Si    331284
No    203665
-     24009
Name: FAMI_TIENEINTERNET, dtype: int64

In [7]:
pd.value_counts(dataset['FAMI_NUMLIBROS'])

0 A 10 LIBROS        212037
11 A 25 LIBROS       158610
26 A 100 LIBROS      111570
MÁS DE 100 LIBROS    38664
-                    37760
Name: FAMI_NUMLIBROS, dtype: int64

In [9]:
pd.value_counts(dataset['FAMI_SITUACIONECONOMICA'])

Igual    334714
Mejor    139318
Peor     74505
-        10499
Name: FAMI_SITUACIONECONOMICA, dtype: int64

In [10]:
pd.value_counts(dataset['ESTU_DEDICACIONLECTURADIARIA'])

30 minutos o menos            205979
Entre 30 y 60 minutos         149862
No leo por entretenimiento    99863
Entre 1 y 2 horas             57681
-                             32496
Más de 2 horas                20787
Name: ESTU_DEDICACIONLECTURADIARIA, dtype: int64

In [13]:
pd.value_counts(dataset['COLE_BILINGUE'])

N    466630
-    91546
S    9119
Name: COLE_BILINGUE, dtype: int64

In [14]:
pd.value_counts(dataset['COLE_JORNADA'])

MAÑANA      263298
COMPLETA    98154
UNICA       67479
TARDE       59667
SABATINA    42322
NOCHE       36375
Name: COLE_JORNADA, dtype: int64

In [18]:
pd.value_counts(dataset['PUNT_INGLES'])

45.0     16601
54.0     16493
40.0     16472
46.0     16459
53.0     16387
41.0     16333
39.0     16273
44.0     16162
47.0     16109
43.0     16086
42.0     16075
55.0     16039
52.0     15975
48.0     15867
50.0     15835
51.0     15767
49.0     15708
38.0     15574
56.0     14975
37.0     14800
57.0     13733
36.0     13727
58.0     12658
35.0     12384
34.0     11277
59.0     11228
60.0     10321
33.0     10272
61.0     9112
32.0     9046
31.0     8308
62.0     8242
63.0     7499
30.0     7413
64.0     6761
29.0     6455
65.0     5989
28.0     5653
66.0     5616
67.0     5013
27.0     4896
68.0     4583
69.0     4385
70.0     4326
71.0     4271
72.0     3671
75.0     3572
26.0     3409
74.0     3331
73.0     3232
76.0     2674
25.0     2657
77.0     2413
78.0     2356
24.0     2196
79.0     2079
81.0     1843
80.0     1751
23.0     1657
100.0    1438
82.0     1206
83.0     909
84.0     710
22.0     644
86.0     635
85.0     635
87.0     235
21.0     187
0.0      161
88.0     140
89.0     126
90.0     98
91.0     92
20.0     37
92.0     24
Name: PUNT_INGLES, dtype: int64